"use strict";/* global */ /* eslint-disable */ /* eslint-disable */webpackJsonp([14],{/***/10:(/***/function _(a,b,c){"use strict";function d(){var a=document.querySelector(".js-hero-graphics");setTimeout(function(){a.classList.add("animation")},600)}var e=c(0),f=function(a){return a&&a.__esModule?a:{default:a}}(e),g=window.Power4.easeInOut,h=window.Power4.easeOut,i=new f.default,j=document.querySelector(".js-tru-hero");/**
		 * Hero animation
		 */const k=new IntersectionObserver(a=>{a.forEach(a=>{a.isIntersecting&&(i.addLabel("start"),i.fromTo(".js-hero-sphare",1,{autoAlpha:0},{autoAlpha:1,ease:g}),i.fromTo(".js-tru-logo",1,{y:"-10px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=0.35"),i.staggerFromTo(".js-hero-heading span",.5,{y:"-40px",autoAlpha:0},{y:"0",autoAlpha:1,onComplete:d},.15,"start-=0.1"),0<a.intersectionRatio&&k.unobserve(a.target))})},{threshold:"0.25"});k.observe(j);/**
		 * about section animation
		 */var l=document.querySelector(".js-about-section"),m=new f.default;const n=new IntersectionObserver(a=>{a.forEach(a=>{a.isIntersecting&&(m.addLabel("start"),m.staggerFromTo(".js-about-content p",1,{y:"-10px",autoAlpha:0},{y:"0",autoAlpha:1},.15,"start+=1"),0<a.intersectionRatio&&n.unobserve(a.target))})},{threshold:"0.25"});n.observe(l);/**
		 * download form animation
		 */var o=document.querySelector(".js-tru-form-section"),p=new f.default;const q=new IntersectionObserver(a=>{a.forEach(a=>{a.isIntersecting&&(p.addLabel("start"),p.fromTo(".js-tru-from-heading",1,{y:"-10px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g}),p.staggerFromTo(".js-form-list li",.5,{y:"-10px",autoAlpha:0},{y:"0",autoAlpha:1},.15,"start+=0.25"),p.fromTo(".js-form-box",1.25,{y:"-10px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=0.25"),0<a.intersectionRatio&&q.unobserve(a.target))})},{threshold:"0.25"});q.observe(o);/**
		 * slides animation
		 */var r,s,t,u,v,w,x,y,z;document.querySelectorAll(".js-slide").forEach(a=>{const b=new IntersectionObserver(c=>{c.forEach(c=>{c.isIntersecting&&(r=new f.default,s=a.querySelectorAll(":scope ".concat(".q-tru-slide-count")),t=a.querySelectorAll(":scope ".concat(".q-tru-slide-box--inner")),r.fromTo(s,1,{y:"-70px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=0.25"),r.fromTo(t,1,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=0.25"),a.classList.contains("willAnimate")&&(u=a.querySelectorAll(":scope ".concat(".js-slide-heading span")),v=a.querySelector(":scope ".concat(".js-slide-graphics")),w=a.querySelectorAll(":scope ".concat(".js-slide-txt")),x=a.querySelectorAll(":scope ".concat(".js-slide-txt-1")),y=a.querySelectorAll(":scope ".concat(".js-slide-txt-2")),z=a.querySelector(":scope ".concat(".js-slide-img")),r.staggerFromTo(u,.55,{y:"-10px",autoAlpha:0},{y:"0",autoAlpha:1},.15,"start+=0.65"),setTimeout(function(){v.classList.add("animation")},1200),r.fromTo(w,1,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=0.95"),r.fromTo(x,1,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=1.05"),r.fromTo(y,1,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=1.25"),r.fromTo(z,1,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:g},"start+=1.05")),0<c.intersectionRatio&&b.unobserve(c.target))})},{threshold:"0.35"});b.observe(a)})}),/***/30:(/***/function _(){// removed by extract-text-webpack-plugin
/***/}),/***/64:(/***/function _(a,b,c){c(10),a.exports=c(30)})},[64]),function(){"use strict";/**
	 * jump to download report section
	 */var a=document.querySelector(".js-goto-report"),b=document.querySelector(".js-tru-form-section"),c=b.getBoundingClientRect().top,d=c+window.pageYOffset-80;a.addEventListener("click",()=>{window.scrollTo({top:d,behavior:"smooth"})});var e=document.querySelector(".js-goto-report-section"),b=document.querySelector(".js-tru-form-section"),c=b.getBoundingClientRect().top,d=c+window.pageYOffset-80;e.addEventListener("click",()=>{window.scrollTo({top:d,behavior:"smooth"})});/**
	 * slides paging
	 */var f,g,h,i,j;document.querySelectorAll(".js-paging").forEach(a=>{a.addEventListener("click",()=>{f=a.getAttribute("data-slide"),console.log(f),g=".js-slide-"+f,h=document.querySelector(g),i=h.getBoundingClientRect().top,j=i+window.pageYOffset-"60",window.scrollTo({top:j,behavior:"smooth"})})})}();
//# sourceMappingURL=index.js.map