"use strict";/* global Swiper:false  */(function(){"use strict";// swiper for testimonial
//sort cards as per popularity
function a(){const a=[],c=[];document.querySelectorAll(".source-checkboxes input[type=\"checkbox\"]:checked").forEach(b=>{a.push(b.value),c.push(b.name)});const d=f.value.toLowerCase();let e=!1;// Flag to check if any card is visible
g.forEach(f=>{const g=c.map(a=>f.getAttribute("data-".concat(a))||""),h=g.flatMap(a=>a.includes(",")?a.split(","):[a]),i=0===a.length||h.some(b=>a.includes(b)),j=""===d||b(f,d),k=i&&j;// Display "No Results" message if no card is visible
f.style.display=k?"block":"none",k&&(e=!0)});// Display "No Results" message if no card is visible
const h=document.getElementById("noResultsMessage");h.style.display=e?"none":"block"}// Function to check if card matches search term
function b(a,b){const c=a.querySelector(".card-head");if(c){const a=c.textContent.toLowerCase();return a.includes(b)}return!1}// Logic to hide Read more anchor and expand desc whose href is equal to #
let c=null;const d=()=>{c=new Swiper(".js-testimonial-container",{slidesPerView:1,centeredSlides:!1,autoplay:{delay:3500,// duration of each slide in ms
disableOnInteraction:!1,pauseOnMouseEnter:!0},loop:!0,pagination:{el:".js-testimonial-container .swiper-pagination",clickable:!0}})},e=()=>{!c&&document.querySelector(".js-testimonial-container")&&d()};(function(){const a=document.querySelector(".grid-cards"),b=Array.from(a.querySelectorAll(".connector-card"));// Check if allCards is an array and not empty before sorting
Array.isArray(b)&&0<b.length&&(b.sort(function(c,a){const b=parseFloat(c.getAttribute("data-supportingdata"))||0,d=parseFloat(a.getAttribute("data-supportingdata"))||0;return d-b}),b.forEach(function(b){a.appendChild(b)}))})();// Search Bar
const f=document.getElementById("searchInput"),g=document.querySelectorAll(".connector-card");f.addEventListener("input",function(){const a=f.value.toLowerCase();g.forEach(b=>{const c=b.querySelector(".card-head");if(c){const d=c.textContent.toLowerCase(),e=d.includes(a)?"block":"none";b.style.display=e}})});// Filters
const h=document.querySelectorAll(".source-checkboxes input[type=\"checkbox\"]");h.forEach(b=>{b.addEventListener("change",a)});const i=document.querySelectorAll(".connector-card a[href='#']");// Logic to smooth Scroll to the explore all connectors
i.forEach(function(a){a.addEventListener("click",function(b){b.preventDefault();const c=a.closest(".connector-card"),d=c.querySelector(".js-card-description");c&&d&&(d.classList.remove("line-clamp-3"),a.classList.replace("block","hidden"))})}),document.addEventListener("click",function(a){if(a.target.closest("#explore-button")){a.preventDefault();var b=document.querySelector(".sticky"),c=document.getElementById("explore-now");if(b&&c){var d=b.offsetHeight;c.style.paddingTop=d/5+"px"}c&&c.scrollIntoView({behavior:"smooth"})}}),window.addEventListener("load",e),window.addEventListener("resize",e)})();
//# sourceMappingURL=index.js.map