"use strict";/* global jQuery bodymovin Waypoint TimelineLite MktoForms2 Swiper:false */ // Dashboard slider & animation
// https://github.com/airbnb/lottie-web
// animation data is exported from Adobe After Effects
/*
 * show form on mobile
 */ /*
 * Testimonial quotes slider
 */ // Centered laptop dashboard animation
/*
 * two-panel Marketo form based on the Qualys account question
 */(function(){"use strict";function a(a,b){return bodymovin.loadAnimation({container:document.querySelector(a),renderer:"svg",loop:!1,autoplay:!1,path:b})}var b=new Swiper(".dahsboard-slider-container",{autoHeight:!1,navigation:{nextEl:".slider-nav--next",prevEl:".slider-nav--prev",disabledClass:"swiper-nav-disabled"},pagination:{el:".swiper-pagination-dashboard",type:"bullets"},loop:!0,autoplay:!1}),c=a(".dahsboard-slide.swiper-slide-duplicate .man-icons-binoculars","/asset/data/apps/asset-inventory/man-icons-binoculars.json"),d=a(".man-icons-binoculars","/asset/data/apps/asset-inventory/man-icons-binoculars.json"),e=!1;// animation 1
// when animation 1 has been downloaded, only then download and run the other animations
e||(function(a,b,c){var d=!1;new Waypoint({element:document.getElementById(a),offset:b,handler:function handler(a){"down"!==a||d||c.play(),d=!0}})}("slider","60%",d),c.play(),e=!0),d.addEventListener("data_ready",function(){var c=!1,d=!1,e=!1,f=!1,g=!1;b.on("slideChange",function(){if(1==b.realIndex&&!c){// animation 2
var h=a(".man-pointing-icons","/asset/data/apps/asset-inventory/man-pointing-icons.json");h.play(),c=!0}if(2==b.realIndex&&!d){// animation 3
var i=a(".graph","/asset/data/apps/asset-inventory/graph.json");i.play(),d=!0}if(3==b.realIndex&&!e){// animation 4
var j=a(".asset-summary","/asset/data/apps/asset-inventory/asset-summary.json");// wait 0.5s before animating
setTimeout(function(){j.play()},500),e=!0}if(4==b.realIndex&&!f){var k=a(".dahsboard-slide:not(.swiper-slide-duplicate) .asset-inventory","/asset/data/apps/asset-inventory/asset-inventory.json");// wait 0.5s before animating
setTimeout(function(){k.play()},500),f=!0}if(4==b.realIndex&&1==b.previousIndex&&!g){var l=a(".dahsboard-slide.swiper-slide-duplicate .asset-inventory","/asset/data/apps/asset-inventory/asset-inventory.json");// wait 0.5s before animating
setTimeout(function(){l.play()},500),g=!0}})})})(),function(a){"use strict";a(".js-create-account").on("click",function(){a(".q-form").addClass("showForm"),a(".form .js-create-account").addClass("hidden")})}(jQuery),function(){"use strict";// init news and events carousel
new Swiper(".resources-slider-container",{slidesPerView:"auto",navigation:!1,pagination:{el:".swiper-pagination",type:"bullets"},centeredSlides:!1,spaceBetween:30})}(),function(){"use strict";var a=new Swiper(".testimonial-quotes-slider"),b=new Swiper(".testimonial-customer-slider",{autoHeight:!1,navigation:{nextEl:".quote-nav--next",prevEl:".quote-nav--prev",disabledClass:"quote-nav-disabled"},pagination:{el:".quote-pagination",type:"bullets"}});a.controller.control=b,b.controller.control=a}(),function(){var a=new TimelineLite,b=window.Power4.easeInOut,c=!1,d=document.querySelector("#ai-dashboard-1 .q-laptop");d.classList.add("q-laptop--will-animate"),new Waypoint({element:document.getElementById("ai-dashboard-1"),offset:"45%",handler:function handler(d){"down"!==d||c||a.addLabel("start").fromTo("#ai-dashboard-1 .q-laptop",.75,{x:"10%",autoAlpha:0},{x:"0%",autoAlpha:1,ease:b}),c=!0}})}(),function(a,b){"use strict";b.whenRendered(function(b){var c,d,e,f,g,h,i,j;c=a("input[name=qualysAccount]"),0<c.length&&(g=b.getFormElem(),a(".q-mktoFormSet > *").unwrap(),d=0<g.find(".mktoButtonNext").length?g.find(".mktoButtonNext").closest(".mktoButtonRow"):g.find("input[name=qualysAccount]").closest(".mktoFormRow"),h=d.prevAll().addBack(),i=d.nextAll(),h.wrapAll("<div class='q-mktoFormSet panel1'/>"),i.wrapAll("<div class='q-mktoFormSet panel2'/>"),g.addClass("show-first-panel"),f=c.closest(".mktoRadioList"),f.replaceWith(f.get(0).cloneNode(!0)),e=a("input[name=qualysAccount]:checked").val(),e&&(j=a("input[name=qualysAccount]").closest(".mktoFormRow").prevAll().find("input[type!=hidden]:not(.mktoValid)"),0===j.length&&(g.removeClass("show-first-panel"),g.addClass("show-next-panel"))))}),b.whenReady(function(b){var c,d,e,f;// save for later
if(c=b.getFormElem(),d=c.find("input[name=qualysAccount]"),0<d.length){var g=a("html").attr("lang"),h="Next",i="Back";"fr"===g?(h="Suivant",i="Pr\xE9c\xE9dent"):"de"===g&&(h="Weiter",i="Zur\xFCck"),e=d.closest(".mktoFormRow"),e.after("<div class=\"mktoButtonRow\"><span class=\"mktoButtonWrap mktoInset\"><button type=\"button\" class=\"mktoButton mktoButtonNext\">"+h+"</button></span></div>"),a(".mktoButtonNext").on("click",function(){var e,f;// validate visible fields
if(b.validate(),e=a("input[name=qualysAccount]:checked").val(),e)b.getValues().qualysAccount===e?e&&(f=a("input[name=qualysAccount]").closest(".mktoFormRow").prevAll().find("input[type!=hidden]:not(.mktoValid)"),0===f.length&&(c.removeClass("show-first-panel"),c.addClass("show-next-panel"))):("yes"===e&&("/apps/global-assetview/form/"===window.location.pathname?window.location.href="../confirm-existing/":window.location.href="confirm-existing/"),b.setValues({qualysAccount:e}));else{// show error message for Qualys Account field
var g=d.parents(".mktoFieldWrap");b.showErrorMessage("This field is required.",g)}}),f=c.find("button[type=submit]"),f.before("<button type=\"button\" class=\"mktoButton mktoButtonBack\">"+i+"</button>"),a(".mktoButtonBack").on("click",function(){c.addClass("show-first-panel"),c.removeClass("show-next-panel")})}b.onSubmit(function(b){var c,d;c=b.getFormElem(),d=a("input[name=qualysAccount]").closest(".mktoFormRow").prevAll().find("input[type!=hidden]:not(.mktoValid)"),0<d.length&&(c.addClass("show-first-panel"),c.removeClass("show-next-panel"))})})}(jQuery,MktoForms2);
//# sourceMappingURL=index.js.map