"use strict";window.qualys=window.qualys||{},function(){"use strict";/*
	 * return object with param names and values
	 */ /*
	 * return array of objects with cookie names and values
	 */window.qualys=window.qualys||{},window.qualys.parseQueryString=function(a){var b,d,e,f,g,h,j,k,m;for(a=a||"",d=!0,e=f="",b={},g=a.split(""),(j=0,k=g.length);j<k;j+=1)h=g[j],"?"===h&&0===j||"&"===h||";"===h?d=!0:"="===h?d=!1:d?e+=h:f+=h,("&"===h||";"===h||j===k-1)&&(m={key:decodeURIComponent(e.replace(/\+/g," ")),value:decodeURIComponent(f.replace(/\+/g," "))},b[m.key]=b.hasOwnProperty(m.key)?b[m.key]instanceof Array?b[m.key].concat(m.value):[b[m.key]].concat(m.value):m.value,e=f="");return b},window.qualys=window.qualys||{},window.qualys.parseCookieString=function(a){var b;// basic DoS preventation
if(81920<a.length)throw new Error("Cookie string too long. length = "+a.length);return b=a.split(/;\s*/).map(function(a){// basic DoS preventation
if(4096<a.length)throw new Error("Cookie too big. length = "+a.length);return{name:a.slice(0,a.indexOf("=")),value:a.slice(a.indexOf("=")+1)}}),b}}(),function(){"use strict";// get url query string parameters
var a=qualys.parseQueryString(window.location.search);// loop over each url query string parameter
Object.entries(a).forEach(a=>{let[b,c]=a;// console.log(`${key}: ${value}`);
b=b.toLowerCase(),b.startsWith("utm_")&&(document.cookie=["qualys.".concat(b,"=").concat(c),//"domain=.qualys.com",
"path=/","secure=yes"].join("; "))});// get all cookies
var b=qualys.parseCookieString(document.cookie),c=[];// loop over each cookie
b.forEach(a=>{// save each UTM cookie in the utms array
if(a.name.startsWith("qualys.utm_")){var b=a.name.replace("qualys.",""),d={};d[b]=a.value,c.push(d)}});// console.log(utms);
// find all links in page that have the class "appendUTM"
var d,e=document.querySelectorAll(".appendUTM"),f=Array.from(e);// convert NodeList to array
// loop over matching links
for(d of f){// get the link href value
var g=d.getAttribute("href"),h=new URL(g);// loop over each UTM parameter found in cookies
for(const a in c)// console.log(index, utms[index]);
for(const[b,d]of Object.entries(c[a]))// console.log(key, value);
// set the utm name/value pair in the query string
h.searchParams.set(b,d);// console.log(url.href);
// update the href value
d.setAttribute("href",h.href)}}(),function(){"use strict";/**
	 * generateUUID - create a random UUID string
	 * @returns {String} uuid
	 */window.qualys=window.qualys||{},window.qualys.utils=window.qualys.utils||{},window.qualys.utils.generateUUID=function(){var a,b;return a="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx",b=a.replace(/[xy]/g,function(a){var b,c;return b=0|16*Math.random(),c="x"===a?b:8|3&b,c.toString(16)}),b}}(),function(){"use strict";// initiate tippy
tippy("[data-tippy-content]"),function(a){a.fn.scrollAndHighlight=function(){function b(){var b=a(window).scrollTop();c.removeClass("active"),c.each(function(){var c=a(this).attr("href"),d=a(c);if(d.length){var e=d.offset().top-100,f=e+d.outerHeight();b>=e&&b<f&&a(this).addClass("active")}})}var c=a(".js-q-sticky-nav");c.click(function(b){b.preventDefault();var c=a(this).attr("href"),d=a(c),e=d.offset().top;a("html, body").animate({scrollTop:e-80},1e3)});var d=_.debounce(b,40);// Highlight the link on page load
a(window).scroll(function(){d()}),b()},a(document).ready(function(){0<a(".js-q-sticky-nav").length&&a(".js-q-sticky-nav").scrollAndHighlight()})}(jQuery),function(a){a(document).ready(function(){a(".js-global-menu").each(function(){// var position, leftPos = 0, width = 0, newLeft, newWidth, firstEl = true;
var b,c,d=0,e=0,f=!0,g=a(this),h=g.parents("nav"),i=h[0].getBoundingClientRect(),j=g.parents(".js-megamenu"),k=g.find(".menu-item");g.append("<span class='item-underline absolute bg-primary-4 h-1 bottom-0 origin-center'></span>");var l=g.find(".item-underline");l.width(0).css("left",0),k.each(function(){var d=a(this),e=d.data("menu"),g=d.parents(".js-megamenu").find(".megamenu-wrap ."+e),h=g.parent(),k=d[0].getBoundingClientRect(),m=g[0].getBoundingClientRect(),n=d.parents(".js-megamenu").find(".megamenu-bg"),o=d.parents(".js-megamenu").find(".megamenu-wrap");d.on("mouseenter",function(){//- Set sub menu style
//- Set current sub menu style
"platform"===e?n.css({left:0,transform:"unset"}):"login"===e||"contact"===e?n.css({right:0,transform:"unset"}):"community"===e?n.css({right:195,transform:"unset"}):"more"===e?n.css({left:"50%",transform:"translateX(-50%)"}):n.css({left:k.left-i.left+"px",transform:"unset"}),n.css("width",m.width+"px"),n.css("height",m.height+"px"),o.css("opacity",1),"platform"===e?o.css({left:0,transform:"unset"}):"login"===e||"contact"===e?o.css({right:0,transform:"unset"}):"community"===e?o.css({right:195,transform:"unset"}):"more"===e?o.css({left:"50%",transform:"translateX(-50%)"}):o.css({left:k.left-i.left+"px",transform:"unset"}),o.css("width",m.width+"px"),o.css("height",m.height+"px"),h.css("opacity",1),j.addClass("dropdown-active"),setTimeout(function(){j.addClass("dropdown-active-ani")},200),a(".menu-item").removeClass("active"),d.addClass("active"),a(".megamenu-item").removeClass("active"),h.addClass("active"),f&&(f=!1,l.css("left",d.position().left)),b=d.position().left,c=d.width(),l.stop().animate({left:b,width:c})}),j.on("mouseleave",function(){a(".megamenu-item").removeClass("active").css("opacity",0),j.removeClass("dropdown-active"),j.removeClass("dropdown-active-ani"),d.removeClass("active"),f=!0,l.stop().animate({width:0})})})})})}(jQuery),function(a){a(document).ready(function(){var b=a("#q-mobile-menu").slideMenu();a(".js-close-menu").on("click",function(){setTimeout(function(){b.navigateTo(".topLevel")},300)})})}(jQuery);// Accouncement carousel swiper configuration
const a=document.querySelector(".js-q-announcements");if(a){const b=new Swiper(".js-q-announcements",{direction:"vertical",loop:!0,autoplay:{delay:1e4,disableOnInteraction:!1// This prevents autoplay from stopping when the user interacts with the swiper
},pagination:!1,on:{afterInit:function afterInit(){a.classList.remove("opacity-0")}}});// Event handler for mouseenter (mouseover)
// Event handler for mouseleave (mouseout)
b.el.addEventListener("mouseenter",()=>{b.autoplay.stop()}),b.el.addEventListener("mouseleave",()=>{b.autoplay.start()})}/**
	 * image with content accordion
	 */(function(a){a(document).ready(function(){a(".js-q-accordion").length&&a(".js-q-accordion").accordiom({speed:500,showFirstItem:!0,autoClosing:!0,openAll:!1,buttonBelowContent:!1,beforeChange:function beforeChange(b){if(!b.classList.contains("on")){var c=b.getAttribute("data-image"),d=a(".js-accordion-images img."+c);a(".accordionImage").not(".active").hide(),d.hasClass("active")||a(".accordionImage.active").fadeOut("fast",function(){a("."+c).fadeIn("slow").addClass("active")}).removeClass("active")}},afterchange:function afterchange(){},onLoad:function onLoad(){a(".js-accordion-images").children(".accordionImage").first().removeClass("hidden").addClass("active")}})})})(jQuery);// Swiper for Related Products
let b=null;const c=()=>{b=new Swiper(".products-container",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:768>=window.innerWidth?12:32})},d=()=>{if(768>=window.innerWidth)!b&&document.querySelector(".products-container")&&c();else if(null!==b){if(Array.isArray(b))for(let a of b)a.destroy();else b.destroy();b=null}};window.addEventListener("load",d),window.addEventListener("resize",_.debounce(d,40));// Swiper for More Reasons to Try
let e=null;const f=()=>{e=new Swiper(".solutions-container",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:16})};window.addEventListener("load",()=>{!e&&document.querySelector(".solutions-container")&&f()});// Swiper for More Reasons to Try -- grey grid
let g=null;const h=()=>{g=new Swiper(".grey-grid-container",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:12})},i=()=>{if(768>=window.innerWidth)!g&&document.querySelector(".grey-grid-container")&&h();else if(null!==g){if(Array.isArray(g))for(let a of g)a.destroy();else g.destroy();g=null}};window.addEventListener("load",i),window.addEventListener("resize",_.debounce(i,40));// Swiper for customerStories
let j=null;const k=()=>{j=new Swiper(".customerStories",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:16})};window.addEventListener("load",()=>{!j&&document.querySelector(".customerStories")&&k()}),function(a){a(document).ready(function(){a(".faqButton").length&&a(".faqButton").each(function(){var b=a(this),c=b.next();b.on("click",function(){c.slideToggle("fast"),b.toggleClass("active")})})})}(jQuery),function(a){a(document).ready(function(){var b=a(".js-mm-filter"),c=a(".js-mm-apps-grid"),d=a("#q_platformApp_label"),e=a(".megamenu-bg");b.length&&(a(".js-mm-filter").on("mouseenter",function(){var b=a(this),f=b.attr("data-col"),g=a(".js-mm-app[data-cat='"+f+"']");// enable active tab
"all"===f?!c.hasClass("q-mm-apps-grid")&&(c.addClass("q-mm-apps-grid"),a(".js-mm-col").addClass("q-mm-col"),a(".js-mm-app").removeClass("hidden"),a(".js-mm-app").removeClass("activeCol"),d.removeClass("hidden"),e.removeClass("showFiletredItem")):(c.removeClass("q-mm-apps-grid"),a(".js-mm-app").addClass("hidden"),g.removeClass("hidden"),a(".js-mm-col").removeClass("q-mm-col"),g.addClass("activeCol"),d.addClass("hidden"),e.addClass("showFiletredItem")),a(".js-mm-filter").not(b).removeClass("active"),b.addClass("active")}),a(".js-megamenu").on("mouseleave",function(){a(".js-mm-filter").removeClass("active"),a(".js-mm-filter[data-col='all']").addClass("active"),a(".js-mm-app").removeClass("hidden"),a(".js-mm-col").addClass("q-mm-col"),a(".js-mm-app").removeClass("activeCol"),d.removeClass("hidden"),e.removeClass("showFiletredItem"),c.hasClass("q-mm-apps-grid")||c.addClass("q-mm-apps-grid")}))})}(jQuery),function(a){// play the targeted video (and hide the poster frame)
function b(a){var b=a.find(".js-videoIframe"),c=a.data("src");// hide poster
a.addClass("videoWrapperActive"),b.append("<iframe class=\"absolute top-0 left-0 right-0 bottom-0 w-full h-full bg-transparent overflow-hidden\" autoplay=\"true\" frameborder=\"0\" allowTransparency=\"true\" allowfullscreen allow=\"autoplay; fullscreen\" src=\"https://player.vimeo.com/video/"+c+"?autoplay=1&title=0&byline=0&portrait=0&share=0\"></iframe>")}// poster frame click event
a(document).on("click",".js-videoPoster",function(c){c.preventDefault();var d=a(this),e=d.closest(".js-videoWrapper");b(e)})}(jQuery);// Swiper for image text container
let l=null;const m=()=>{l=new Swiper(".image-text-container",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:12})},n=()=>{if(768>=window.innerWidth)!l&&document.querySelector(".image-text-container")&&m();else if(null!==l){if(Array.isArray(l))for(let a of l)a.destroy();else l.destroy();l=null}};window.addEventListener("load",n),window.addEventListener("resize",n);//Testimonial Dekstop Swiper Slider
// let customerTestimonialSwiper = null;
// let codeHasRun = false;
let o=new Swiper(".js-tm-content-slider",{effect:"slide",pagination:{el:".testimonial-container .swiper-pagination",clickable:!0},on:{init:function init(){const a=this.slides[this.activeIndex];if(a&&a.hasAttribute("data-video")){const b=a.getAttribute("data-video");if(b){const a=document.getElementById(b);a.classList.remove("hidden")}}}}}),p=new Swiper(".js-tm-image-slider",{effect:"fade",allowTouchMove:!1});o.on("slideChange",function(){p.slideTo(o.activeIndex);const a=this.activeIndex,b=this.slides[a],c=b.getAttribute("data-video"),d=document.querySelectorAll(".js-home-play-btn");for(const a of d)a.classList.add("hidden");var e;c&&(e=document.getElementById(c),e.classList.remove("hidden"))}),p.on("slideChange",function(){o.slideTo(p.activeIndex)});//Testimonial Mobile Swiper Slider
let q=null;const r=()=>{q=new Swiper(".mobile-testimonial-container",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:20,pagination:!1})},s=()=>{if(768>=window.innerWidth)!q&&document.querySelector(".mobile-testimonial-container")&&r();else if(null!==q){if(Array.isArray(q))for(let a of q)a.destroy();else q.destroy();q=null}};window.addEventListener("load",s),window.addEventListener("resize",s);//Swiper for Cyber Risk Container cards
let t=null;const u=()=>{t=new Swiper(".cyber-risk-container",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:28})},v=()=>{if(768>=window.innerWidth)!t&&document.querySelector(".cyber-risk-container")&&u();else if(null!==t){if(Array.isArray(t))for(let a of t)a.destroy();else t.destroy();t=null}};window.addEventListener("load",v),window.addEventListener("resize",v);//Swiper for worldWide container
let w=null;const x=()=>{w=new Swiper(".protection-worldwide",{slidesPerView:"auto",centeredSlides:!1,spaceBetween:28,pagination:{el:".protection-worldwide .swiper-pagination",clickable:!0}})},y=()=>{if(768>=window.innerWidth)!w&&document.querySelector(".protection-worldwide")&&x();else if(null!==w){if(Array.isArray(w))for(let a of w)a.destroy();else w.destroy();w=null}};window.addEventListener("load",y),window.addEventListener("resize",y)}();/**
 * Select a random image everytime on page load to use in the
 * trail forms CTA
 */ // Function to get a random variable different from the previous one
function getRandomVariable(a){const b=["1","2","3","4","5","6","7","8"];let c;do c=b[Math.floor(Math.random()*b.length)];while(c===a);return c}// Function to set and get the previously chosen variable
function setPreviousVariable(a){localStorage.setItem("previousVariable",a)}function getPreviousVariable(){return localStorage.getItem("previousVariable")}// On page load
window.onload=function(){// Get the previously chosen variable
const a=getPreviousVariable(),b=getRandomVariable(a),c=document.querySelector(".js-bgimage-container");// Get a new random variable different from the previous one
// bg image container
c&&(c.style.backgroundImage="url(\"https://ik.imagekit.io/qualys/image/background/bg-image-"+b+".jpg\")",setPreviousVariable(b))},function(a){a(document).ready(function(){function b(a){// hide all inner contents
h.addClass("hidden"),h.eq(a).removeClass("hidden"),i.hide(),i.eq(a).slideDown()}function c(a){a!==l&&(g.removeClass("isActive"),g.eq(a).addClass("isActive"),l=a,b(a))}function d(){l=(l+1)%g.length,b(l),g.removeClass("isActive"),g.eq(l).addClass("isActive")}function e(){768<=a(window).width()&&(k=setInterval(d,5e3))}function f(){clearInterval(k),e()}// Add event listeners for mouseover and mouseout on tabs
const g=a(".js-q-laptop-tab"),h=a(".js-q-tab-content"),i=a(".inner-content"),j=a(".js-featured-laptop");let k,l=0;g.on("click",function(){c(g.index(this))}),j.on("mouseover",function(){clearInterval(k)}),j.on("mouseout",function(){e()}),e(),a(window).on("resize",function(){f()})})}(jQuery),function(){document.addEventListener("DOMContentLoaded",function(){var a=document.querySelectorAll(".js-laptop-swiper");a&&a.forEach(function(a){new Swiper(a,{slidesPerView:1,navigation:!1,autoplay:!0,loop:!0})})})}();/**
 * testimonial section background video
 */const videoElement=document.getElementById("q_testimonial_video_bg"),videoFiles=["video-bg-1.webm","video-bg-2.webm","video-bg-3.webm","video-bg-4.webm","video-bg-5.webm","video-bg-6.webm","video-bg-7.webm"];// Function to shuffle the array randomly
function shuffleArray(a){for(let b=a.length-1;0<b;b--){const c=Math.floor(Math.random()*(b+1));[a[b],a[c]]=[a[c],a[b]]}}let currentIndex=0,selectedVideos=[];// Function to select 3 random videos
function selectRandomVideos(){// Copy the array
selectedVideos=videoFiles.slice(),shuffleArray(selectedVideos),selectedVideos=selectedVideos.slice(0,3)}// Function to set the next video source
function setNextVideo(){// Increment the index for the next video in the sequence
// Event listener for when the current video ends
currentIndex>=selectedVideos.length&&(currentIndex=0),videoElement.src="https://cdn2.qualys.com/videos/background/"+selectedVideos[currentIndex],currentIndex++,videoElement.addEventListener("ended",setNextVideo)}/**
 * Testimonials carousel global function
 */ /**
 * tabs swiper
 */ /**
 * laptop tabs swiper
 */ /**
 * Reasons to switch to Qualys slider
 */ /**
 * a day in the life slider
 */videoElement&&(selectRandomVideos(),setNextVideo()),function(){"use strict";// swiper for testimonial
let a=null;const b=document.querySelector(".js-testimonial-container"),c=()=>{a=new Swiper(".js-testimonial-container",{slidesPerView:1,centeredSlides:!1,autoplay:{delay:3500,// duration of each slide in ms
disableOnInteraction:!1,pauseOnMouseEnter:!0},loop:!0,pagination:{el:".js-testimonial-swiper-pagination",clickable:!0}})},d=()=>{!a&&document.querySelector(".js-testimonial-container")&&c()};b&&(window.addEventListener("load",d),window.addEventListener("resize",d))}(),function(){"use strict";var a=document.querySelector(".js-swiper-tabs");// Check if the parent container exists
if(a){// Get all children with the class ".tab"
var b=a.querySelectorAll(".tab"),c=[];// Create an array to store the text content of each child
// Loop through each child and push its text content to the array
b.forEach(function(a){var b=a.textContent.trim().replace(/\s+/g," ");c.push(b)});let f=null;var d=document.querySelector(".js-swiper-tabs-slider"),e="true"===d.getAttribute("data-autoplay");const g=()=>{f=new Swiper(".js-swiper-tabs-slider",{slidesPerView:1,autoplay:!!e&&{delay:3e3,disableOnInteraction:!1,pauseOnMouseEnter:!0},pagination:{el:".js-swiper-tabs",clickable:!0,renderBullet:function renderBullet(a,b){return"<div class=\""+b+"\">"+c[a]+"</div>"}}})},h=()=>{!f&&document.querySelector(".js-swiper-tabs-slider")&&g()};window.addEventListener("load",h),window.addEventListener("resize",h)}}(),function(){"use strict";var a=document.querySelector(".js-swiper-laptop-tabs");// Check if the parent container exists
if(a){// Get all children with the class ".tab"
var b=a.querySelectorAll(".tab"),c=[];// Create an array to store the text content of each child
// Loop through each child and push its text content to the array
b.forEach(function(a){var b=a.textContent.trim().replace(/\s+/g," ");c.push(b)});let f=null;var d=document.querySelector(".js-swiper-laptop-tabs-slider"),e="true"===d.getAttribute("data-auoplay");const g=()=>{f=new Swiper(".js-swiper-laptop-tabs-slider",{slidesPerView:1,autoplay:!!e&&{delay:3e3,disableOnInteraction:!1,pauseOnMouseEnter:!0},pagination:{el:".js-swiper-laptop-tabs",clickable:!0,renderBullet:function renderBullet(a,b){return"<div class=\""+b+"\">"+c[a]+"</div>"}}})},h=()=>{!f&&document.querySelector(".js-swiper-laptop-tabs-slider")&&g()};window.addEventListener("load",h),window.addEventListener("resize",h)}}(),function(){"use strict";let a=null;const b=document.querySelector(".js-reasons-container"),c=()=>{a=new Swiper(".js-reasons-container",{slidesPerView:1,centeredSlides:!0,autoplay:{delay:3500,// duration of each slide in ms
disableOnInteraction:!1,pauseOnMouseEnter:!0},loop:!0,pagination:{el:".js-reasons-swiper-pagination",clickable:!0}})},d=()=>{!a&&document.querySelector(".js-reasons-container")&&c()};b&&(window.addEventListener("load",d),window.addEventListener("resize",d))}(),function(){"use strict"}();
//# sourceMappingURL=global-scripts.js.map