"use strict";(function(){"use strict";/*
	 * helper functions to escape a string for safe output in HTML
	 * https://stackoverflow.com/a/7124052/2367550
	 */function a(a){return a.replace(/[&<>"'/]/g,function(a){var b={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"};return b[a]})}// use XMLHttpRequest
function b(){var b,d,e,f,g,i,j,l;try{if(b=JSON.parse(this.responseText),b&&"SearchResponse"===b._type){if(f=document.getElementById("results"),!b.webPages)return void(f.innerHTML="<ol id=\"b_results\" role=\"main\" \t\t\t\t\taria-label=\"Search Results\"><li class=\"b_no\" \t\t\t\t\tdata-bm=\"4\"><h1>There are no results for \t\t\t\t\t<strong>"+a(b.queryContext.originalQuery)+"</strong> \t\t\t\t\t</h1><ul><li><span>Check your spelling or try different \t\t\t\t\tkeywords</span> </li></ul></li></ol>");// add the number of results
if(i=b.webPages.totalEstimatedMatches||0,1e3<i&&(i=i%1e3+1e3),0<k){k=parseInt(k,10),h=parseInt(h,10);var m=k+1,n=k+h;n>i&&(n=i),m>i&&(m=1+n-h),l=[m.toLocaleString()+"\u2013",n.toLocaleString()," of "+i.toLocaleString()].join("")}else l=i.toLocaleString();for(f.innerHTML="<div id=\"b_tween\">\t\t\t\t<span class=\"sb_count\" data-bm=\"4\">"+l+" \t\t\t\tresults</span></div>",d=b.webPages.value.length||0,0<d&&(j=document.createElement("ol"),j.id="b_results",j.setAttribute("role","main"),j.setAttribute("aria-label","Search Results"),f.appendChild(j)),e=0;e<d;e+=1)g=b.webPages.value[e],g.displayUrl.match(/\.pdf$/)&&(g.isPDF=!0),j.innerHTML+="<li class=\"b_algo\" data-bm=\"7\">\t\t\t\t\t<div class=\"b_title\">\t\t\t\t\t"+(g.isPDF?"<span class=\"sb_doct_txt b_float\">[PDF]</span>":"")+"\t\t\t\t\t<h2 class=\"heading--4\">\t\t\t\t\t<a class=\"q-link\" href=\""+g.url+"\">\t\t\t\t\t"+g.name+"\t\t\t\t\t</a></h2></div><div class=\"b_caption\">\t\t\t\t\t<div class=\"b_attribution\"><cite>\t\t\t\t\t"+g.displayUrl+"\t\t\t\t\t</cite></div><p>\t\t\t\t\t"+a(g.snippet)+"\t\t\t\t\t</p></div></li>";// attach pagination UI elements
i>h&&j.appendChild(c(i))}else throw new Error("Unexpected response: "+this.responseText)}catch(a){throw a}}function c(b){var c,e,f,g,j,l,m,n,o,p,q;// calculate how many pages of results there are
n=Math.ceil(b/h),c=document.createElement("li"),c.className="b_pag",c.setAttribute("data-bm",17),e=document.createElement("nav"),e.setAttribute("role","navigation"),c.appendChild(e),f=document.createElement("h4"),f.innerHTML="Pagination",f.className="b_hide",e.appendChild(f),g=document.createElement("ul"),g.className="sb_pagF",g.setAttribute("aria-label","More pages with results"),e.appendChild(g),o=k/h+1,p=o-2,1>p&&(p=1),q=p+4;// generate up to 5 page links based on total estimated matches
for(var r=p;r<=q;r+=1)r<=n&&(j=document.createElement("li"),l=document.createElement("a"),l.innerHTML=r,r===o?l.className="sb_pagS":(l.setAttribute("aria-label","Page "+r),l.href="#page-"+r,l.addEventListener("click",d)),g.appendChild(j.appendChild(l)));// generate prev/next links
return 1<p&&(j=document.createElement("li"),l=document.createElement("a"),l.className="sb_pagP",l.title="Previous page",l.href="#prev",l.addEventListener("click",d),m=document.createElement("div"),m.className="sw_prev",m.innerHTML="\u25C4",l.appendChild(m),j.appendChild(l),g.insertBefore(j,g.childNodes[0])),q<n&&(j=document.createElement("li"),l=document.createElement("a"),l.className="sb_pagN",l.title="Next page",l.href="#next",l.addEventListener("click",d),m=document.createElement("div"),m.className="sw_next",m.innerHTML="\u25BA",l.appendChild(m),j.appendChild(l),g.appendChild(j)),c}// handle pageination
function d(a){var b;a.preventDefault(),b=a.target.classList.contains("sw_prev")?k/h:a.target.classList.contains("sw_next")?k/h+2:parseInt(a.target.innerText,10),k=h*(b-1),f(l,k)}function e(a){a=a.replace(/\s+/g,"+");var b="https://www.google.com/search?q=site%3Aqualys.com+"+a;window.location.href=b}function f(a,c){var d,e,f;// clear old results, if any
e=document.getElementById("results"),e&&(e.innerHTML=""),a=a||document.querySelector("input[name=query]").value,c=c||0,d=new XMLHttpRequest,d.addEventListener("load",b),f=[j,"?query="+encodeURIComponent(a),"&mkt="+(navigator.language||"en-US"),"&count="+encodeURIComponent(h),"&offset="+encodeURIComponent(c)].join(""),d.open("GET",f),d.send()}function g(a){var b;a.preventDefault(),b=a.target.querySelector("input[name=query]"),b&&(l=b.value,k=0),e(l)}// bind the form action to trigger the XMLHttpRequest
var h,i,j,k,l;// get key and config from HTML
i=document.querySelector(".bing"),i&&(h=parseInt(i.getAttribute("data-bing-custom-search-results-per-page"),10)||10),j="https://wj6ny6uen5.execute-api.us-east-1.amazonaws.com/bing-custom-search",k=0;var m=document.querySelector("#search_form");m&&m.addEventListener("submit",g);// look for a offset varialb ein the URL
var n=location.search.match(/first=([0-9]+)([&;#]|$)/);if(n){var o=parseInt(decodeURIComponent(n[1]),10);o&&(k=o-1)}// look for a query variable in the URL
if(n=location.search.match(/q=(.*?)([&;#]|$)/),n){var p=decodeURIComponent(n[1]).replace(/\+/g," ");if(p){// update input value
var q=document.querySelector("input[name=query]");q&&(q.value=p),f(p,k)}}})();
//# sourceMappingURL=index.js.map