"use strict";/* global jQuery:false */ // expand / collapse agenda rows
// agenda tab functionality
// session filter functionality
(function(a){"use strict";a(".title-speaker-container").on("click",function(b){a(b.currentTarget).hasClass("expanded")?(a(b.currentTarget).removeClass("expanded").addClass("collapsed"),a(b.currentTarget).parent(".description").find(".abstract").addClass("hidden")):a(b.currentTarget).hasClass("collapsed")&&(a(b.currentTarget).removeClass("collapsed").addClass("expanded"),a(b.currentTarget).parent(".description").find(".abstract").removeClass("hidden"))})})(jQuery),function(a){"use strict";a(".tablink").on("click",function(b){var c=a(b.currentTarget).attr("data-tab-id");a(".tablink").removeClass("active"),a(b.currentTarget).addClass("active"),a(".tab-content").addClass("hidden"),a("#"+c).removeClass("hidden")});// if hash value containing tab ID exists, trigger a click on the tab
var b=window.location.hash.replace(/#|\//gi,"");a("[data-tab-id=\""+b+"\"]").click()}(jQuery),function(a){"use strict";a(".filter-link").on("click",function(b){a(b.currentTarget).hasClass("active")?a(b.currentTarget).removeClass("active"):a(b.currentTarget).addClass("active");var c=[];// create array of active filters
// hide all sessions
// show filtered sessions
// display no results message
a(".filter-link.active").each(function(b,d){c.push(a(d).attr("data-filter-id"))}),a(".tab-content-wrapper tr").addClass("hidden"),a(".tab-content-wrapper tr").each(function(b,d){var e=a(d).attr("data-filter-id");-1!==a.inArray(e,c)&&a(d).removeClass("hidden")}),a(".agenda-table").each(function(b,c){var d=a(c).find("tr"),e=a(c).find("tr.hidden");d.length==e.length&&a(c).find(".no-results").removeClass("hidden")})}),a(".clear-all a").on("click",function(){a(".filter-link").each(function(b,c){a(c).removeClass("active"),a(".tab-content-wrapper tr").removeClass("hidden"),a(".tab-content-wrapper tr.no-results").addClass("hidden")})})}(jQuery);
//# sourceMappingURL=index.js.map