"use strict";/* global jQuery Swiper */ /* eslint-disable */ /* eslint-enable */ /*
 * Smooth scrolling
 */ // handle app badge slider
webpackJsonp([12],{/***/12:(/***/function _(a,b,c){"use strict";// default hero transition
var d=c(2),e=function(a){return a&&a.__esModule?a:{default:a}}(d);(0,e.default)()}),/***/66:(/***/function _(a,b,c){c(12)})},[66]),function(){"use strict";function a(a){const b=a.currentTarget.hash,c=document.querySelector(b);if(c)setTimeout(function(){c.scrollIntoView({behavior:"smooth",block:"start"})},10);else throw new Error("Element not found for hash: ".concat(b));a.preventDefault()}const b=Array.from(document.querySelectorAll("a[href^='#']"));b.forEach(function(b){b.addEventListener("click",a)})}(),function(a){var b={slidesPerView:10,watchSlidesProgress:!0,watchSlidesVisibility:!0,a11y:!0,grabCursor:!0,spaceBetween:35,breakpoints:{1280:{slidesPerView:8},1024:{slidesPerView:6},990:{slidesPerView:5},480:{slidesPerView:4},340:{slidesPerView:4}}},c=void 0;a(document).ready(function(){var d=window.location.pathname;a("a.q-apps-nav__link[href=\""+d+"\"]").parents(".q-apps-nav__item").addClass("q-apps-nav__item--active"),a(window).on("resize",function(){// function to hide or show slider nav buttons where applicable
function d(){var b=a(".apps-nav-button--prev"),d=a(".apps-nav-button--next");c.isBeginning?b.addClass("hidden"):b.removeClass("hidden"),c.isEnd?d.addClass("hidden"):d.removeClass("hidden")}var e=a(window).width();720<=e&&c===void 0?(c=new Swiper(".swiper-container-nav",b),setTimeout(function(){// get index value from hash, if it exists
var b=window.location.hash.replace("#/index/","");// if index value doesn't exist in URL hash
""===b?c.slideTo(a(".q-apps-nav__item--active").index(),0,!1):c.slideTo(b,0,!1),d(),a(".q-apps-mask").addClass("hide"),setTimeout(function(){a(".q-apps-mask").remove()},500)},0),a(".apps-nav-button--prev").on("click",function(){// slide to left by 3 slides
c.slideTo(c.activeIndex-3,500),d()}),a(".apps-nav-button--next").on("click",function(){// slide to right by 3 slides
c.slideTo(c.activeIndex+3,500),d()}),a(".swiper-slide a").on("click",function(b){b.preventDefault();// get index of first visible badge
var c=a(".swiper-slide-visible").index(),d=a(b.currentTarget).prop("href");// redirect to original URL + hash containing first visible badge index
window.location.href=d+"#/index/"+c})):720>e&&c!==void 0&&(c.destroy(!0,!0),c=void 0)}).resize();// pie swiper
var e=new Swiper(".swiper-container-gdpr",{pagination:{el:".swiper-pagination",clickable:!0},autoplay:{delay:6e3,disableOnInteraction:!0,pauseOnMouseEnter:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});e.on("slideChange",function(){a(".q-grdp__pie-svg").attr("class","q-grdp__pie-svg q-grdp__pie-svg--active-"+e.activeIndex)}),e.init(),a(".q-gdrp__pie, .q-gdrp__pie-text").each(function(){var b=a(this),c=b.data("slide");b.on("click",function(){e.slideTo(c)})})})}(jQuery);
//# sourceMappingURL=index.js.map