"use strict";/* global jQuery */ /* eslint-disable */ /* eslint-enable */ /*
 * automatically open partner overlay based on hash value
 */webpackJsonp([11],{/***/16:(/***/function _(a,b,c){"use strict";function d(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function")}var e=function(){function a(a,b){for(var c,d=0;d<b.length;d++)c=b[d],c.enumerable=c.enumerable||!1,c.configurable=!0,"value"in c&&(c.writable=!0),Object.defineProperty(a,c.key,c)}return function(b,c,d){return c&&a(b.prototype,c),d&&a(b,d),b}}(),f=c(3),g=function(a){return a&&a.__esModule?a:{default:a}}(f);(0,g.default)();var h=function(){function a(){d(this,a),this.el=document.querySelector(".q-partners-filter"),this.select=this.el.querySelector(".q-select"),this.attachEvents()}return e(a,[{key:"attachEvents",value:function(){this.select.addEventListener("change",this.onChange)}},{key:"onChange",value:function(){for(var a=document.getElementById(this.value),b="q-partners-filter__content--active",c=document.querySelectorAll(".q-partners-filter__content"),d=0;d<c.length;d++)c[d].classList.remove(b);a&&a.classList.add(b)}}]),a}(),i=new h;// eslint-disable-line
/***/}),/***/36:(/***/function _(){// removed by extract-text-webpack-plugin
/***/}),/***/70:(/***/function _(a,b,c){c(16),a.exports=c(36)})},[70]),function(a){"use strict";a(document).ready(function(){// get hash value
var b="";window.location.hash&&(b=window.location.hash.substring(1),b=0==b.indexOf("/")?b.substring(1):b);var c=b.replace("partner/","");if("qualys-ticket-notification-engine"==c&&(document.location.href="https://community.qualys.com/api"),c){a("."+c).parents(".q-partners-filter__content").addClass("q-partners-filter__content--active");// get partner element
var d=document.querySelectorAll("."+c+" a");// convert it from a nodelist to an array
// if the element is found
if(d=Array.prototype.slice.call(d),a.isArray(d)&&0<d.length){// trigger a click event on the element using native JS (not jQuery)
var e=document.createEvent("MouseEvent");e.initEvent("click",!0,!0),d[0].dispatchEvent(e)}}})}(jQuery);
//# sourceMappingURL=integration.js.map