"use strict";/* global jQuery MktoForms2 */ /*
 * Get hash tag and check product checkbox
 */ /*
 * two-panel Marketo form based on the Qualys account question
 */ /*
 * Enable fancybox overlay popup
 */(function(a,b){"use strict";function c(){window.location.hash&&window.location.hash.split("/").forEach(function(b){var c,f;// update solutions interested
// update trial package
f=d[b],f&&(a("[value=\""+f+"\"]").prop("checked",!0),a("[value=\""+f+"\"]").trigger("change"),a("input[name=solutionsInterestedOther]").val(f)),c=e[b],c&&(a("[value=\""+c+"\"]").prop("checked",!0),a("[value=\""+c+"\"]").trigger("change"))})}var d={ai:"Asset Inventory",syn:"CMDB Sync",vm:"Vulnerability Management",tp:"Threat Protection",cm:"Continuous Monitoring",was:"Web Application Scanning",waf:"Web Application Firewall",pc:"Policy Compliance",pci:"PCI Compliance",sca:"Security Configuration Assessment",saq:"Security Assessment Questionnaire",ioc:"Indication of Compromise",fim:"File Integrity Monitoring"},e={smb:"Express Lite",sme:"Express",enterprise:"Enterprise",consultant:"Consultant",government:"Federal Government"};a(window).on("hashchange",c),a(document).ready(c),a(document).on("click",".mktoButtonNext",c),b.whenRendered(c)})(jQuery,MktoForms2),function(a,b){"use strict";b.whenRendered(function(b){var c,d,e,f,g,h,i,j;c=a("input[name=qualysAccount]"),0<c.length&&(g=b.getFormElem(),a(".q-mktoFormSet > *").unwrap(),d=0<g.find(".mktoButtonNext").length?g.find(".mktoButtonNext").closest(".mktoButtonRow"):g.find("input[name=qualysAccount]").closest(".mktoFormRow"),h=d.prevAll().addBack(),i=d.nextAll(),h.wrapAll("<div class='q-mktoFormSet panel1'/>"),i.wrapAll("<div class='q-mktoFormSet panel2'/>"),g.addClass("show-first-panel"),f=c.closest(".mktoRadioList"),f.replaceWith(f.get(0).cloneNode(!0)),e=a("input[name=qualysAccount]:checked").val(),e&&(j=a("input[name=qualysAccount]").closest(".mktoFormRow").prevAll().find("input[type!=hidden]:not(.mktoValid)"),0===j.length&&(g.removeClass("show-first-panel"),g.addClass("show-next-panel"))))}),b.whenReady(function(b){var c,d,e,f;// save for later
// check for the qualys account input
c=b.getFormElem(),d=c.find("input[name=qualysAccount]"),0<d.length&&(e=d.closest(".mktoFormRow"),e.after("<div class=\"mktoButtonRow\"><span class=\"mktoButtonWrap mktoInset\"><button type=\"button\" class=\"mktoButton mktoButtonNext\">Next</button></span></div>"),a(".mktoButtonNext").on("click",function(){var e,f;// validate visible fields
if(b.validate(),e=a("input[name=qualysAccount]:checked").val(),e)b.getValues().qualysAccount===e?e&&(f=a("input[name=qualysAccount]").closest(".mktoFormRow").prevAll().find("input[type!=hidden]:not(.mktoValid)"),0===f.length&&(c.removeClass("show-first-panel"),c.addClass("show-next-panel"))):b.setValues({qualysAccount:e});else{// show error message for Qualys Account field
var g=d.parents(".mktoFieldWrap");b.showErrorMessage("This field is required.",g)}}),f=c.find("button[type=submit]"),f.before("<button type=\"button\" class=\"mktoButton mktoButtonBack\">Back</button>"),a(".mktoButtonBack").on("click",function(){c.addClass("show-first-panel"),c.removeClass("show-next-panel")})),b.onSubmit(function(b){var c,d;// show panel1 if there are any invalid fields there
c=b.getFormElem(),d=a("input[name=qualysAccount]").closest(".mktoFormRow").prevAll().find("input[type!=hidden]:not(.mktoValid)"),0<d.length&&(c.addClass("show-first-panel"),c.removeClass("show-next-panel"))})})}(jQuery,MktoForms2),function(a){"use strict";a("[data-fancybox]").fancybox({toolbar:!1,smallBtn:!0,btnTpl:{smallBtn:"<button data-fancybox-close class=\"fancybox-close-small privacy\" title=\"{{CLOSE}}\"></button>"},iframe:{preload:!1}})}(jQuery);
//# sourceMappingURL=index.js.map