"use strict";/* global _ Vimeo TimelineLite Swiper:false */ /* eslint-disable */ /* eslint-enable */ /*
 * testimonial carousel
 */ /*
 * apps tabs
 */ // Toggle cloud platform lists
/*
 * Play video when user clicks poster image
 */webpackJsonp([2],{/***/15:/***/function _(a,b,c){"use strict";function d(a){return a&&a.__esModule?a:{default:a}}// toggle quotes
// homepage js
//var heroDiagram = document.querySelector(".hero-diagram");
function e(){window.CustomEvent?event=new CustomEvent("heroDiagramComplete"):(event=document.createEvent("CustomEvent"),event.initCustomEvent("heroDiagramComplete",!0,!0))}function f(){A=!0}function g(){D=!0}function h(){G=!0}function i(){K=!0}function j(){N=!0}function k(){T=!0}var l=c(0),m=d(l),n=c(1),o=d(n),p=c(56),q=d(p),r=c(4),s=d(r);(0,q.default)();// // animate laptop
// (0, _tp2.default)();
// hero animations
var t=new m.default,u=window.Power4.easeInOut,v=document.querySelector(".q-home-hero"),w=document.querySelector(".q-home__platform-numbers"),x=document.querySelector(".q-home__try"),y=document.querySelector(".q-home-feed"),z=new o.default({// eslint-disable-line
element:v,offset:"100%",handler:function(a){"down"===a&&(t.addLabel("start"),t.fromTo(".q-home-hero__heading .line1",.75,{y:"20px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u},"start+=0.25"),t.fromTo(".q-home-hero__heading .line2",.75,{y:"20px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u},"start+=0.50"),t.fromTo(".q-home-hero__heading .line3",.75,{y:"20px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u},"start+=0.75"),t.fromTo(".q-home-hero__text",1,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u},"start+=1"),t.fromTo(".q-home-hero__cta",1,{autoAlpha:0},{autoAlpha:1,ease:u},"start+=1.25"),t.fromTo(".hero-diagram",1,{x:"30px",autoAlpha:0},{x:"0",autoAlpha:1,ease:u,onComplete:e},"start+=0.85"),t.fromTo(".q-home-hero__graphic-caption",1,{autoAlpha:0},{autoAlpha:1,ease:u},"start+=0.95"))}}),A=!1,B=new m.default,C=new o.default({// eslint-disable-line
element:w,offset:"100%",handler:function(a){"down"!==a||A||B.fromTo(".q-home__platform-numbers-heading",1,{y:"-20%",autoAlpha:0},{y:"0%",autoAlpha:1,ease:window.Power4.easeInOut},.3).staggerFromTo(".q-numbers__item",.8,{y:"20%",autoAlpha:0},{y:"0%",autoAlpha:1,ease:window.Power4.easeInOut,onComplete:f},.2,"-=0.75")}}),D=!1,E=new m.default,F=new o.default({// eslint-disable-line
element:x,offset:"100%",handler:function(a){"down"!==a||D||(E.addLabel("start"),E.fromTo(".q-home__try",.74,{y:"50px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u,onComplete:g},"start+=0.85"),E.fromTo(".q-slab-top",.74,{y:"-30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u,onComplete:g},"start+=1.55"),E.fromTo(".q-slab-middle",.74,{y:"-30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u,onComplete:g},"start+=1.45"),E.fromTo(".q-slab-bottom",.74,{y:"-30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u,onComplete:g},"start+=1.35"),E.fromTo(".q-home__try-heading",.6,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u,onComplete:g},"start+=1.65"),E.fromTo(".q-home__try-text",.8,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u,onComplete:g},"start+=1.65"),E.fromTo(".q-home__try-button",.8,{y:"30px",autoAlpha:0},{y:"0",autoAlpha:1,ease:u,onComplete:g},"start+=1.65"))}}),G=!1,H=new m.default,I=document.querySelector(".asset-inventory-dashboard"),J=new o.default({// eslint-disable-line
element:I,offset:"60%",handler:function(a){"down"!==a||G||H.fromTo("#ai-dashboard-laptop",1,{x:"-25%",autoAlpha:0},{x:"0%",autoAlpha:1,ease:u,onComplete:h})}}),K=!1,L=new m.default,M=document.querySelector(".q-grid__container.intro"),J=new o.default({// eslint-disable-line
element:M,offset:"60%",handler:function(a){"down"!==a||K||L.fromTo(".vm-widget",1,{x:"25%",autoAlpha:0},{x:"0%",autoAlpha:1,ease:u,onComplete:i})}}),N=!1,O=new m.default,P=document.querySelector(".it-security-blocks"),Q=document.querySelector(".q-home__security-panel.left-panel"),R=document.querySelector(".q-home__security-panel.right-panel"),S=new o.default({// eslint-disable-line
element:P,offset:"60%",handler:function(a){"down"!==a||N||(E.addLabel("start"),O.fromTo(Q,1,{y:"50px",autoAlpha:0},{y:"0px",autoAlpha:1,ease:u,onComplete:j},"start+=0.25"),O.fromTo(R,1,{y:"50px",autoAlpha:0},{y:"0px",autoAlpha:1,ease:u,onComplete:j},"start+=0.85"))}}),T=!1,U=new m.default,V=new o.default({// eslint-disable-line
element:y,offset:"100%",handler:function(a){"down"!==a||T||U.staggerFromTo(".q-home-feed__item",1,{y:"20%",autoAlpha:0},{y:"0%",autoAlpha:1,ease:window.Power4.easeInOut,onComplete:k},.1)}}),W=document.querySelector(".q-home__powerful-apps-page-container"),X=new m.default,Y=new o.default({// eslint-disable-line
element:W,offset:"100%",handler:function(a){"down"===a&&X.staggerFromTo(".active-page .q-home-apps__block",1,{y:"20%",autoAlpha:0},{y:"0%",autoAlpha:1,ease:window.Power4.easeInOut},.1)}});/***/},/***/35:/***/function _(){// removed by extract-text-webpack-plugin
/***/},/***/56:/***/function _(a,b){"use strict";Object.defineProperty(b,"__esModule",{value:!0}),b.default=function(a){for(var b=a||document.querySelectorAll(".q-quote-box"),c=function c(a){var d=b[a].querySelector(".q-quote-box__counter"),e=b[a].querySelector(".q-quote-box__counter-current"),f=b[a].querySelectorAll(".q-blockquote");d&&d.addEventListener("click",function(){var c=b[a].querySelector(".q-blockquote--active");c.nextElementSibling?c.nextElementSibling.classList.add("q-blockquote--active"):f[0].classList.add("q-blockquote--active"),c.classList.remove("q-blockquote--active");for(var d=0;d<f.length;d++)f[d].classList.contains("q-blockquote--active")&&(e.innerText=d+1)})},d=0;d<b.length;d++)c(d)}},/***/69:/***/function _(a,b,c){c(15),a.exports=c(35)}},[69]),function(){"use strict";var a=new Swiper(".testimonial-container",{slidesPerView:1,observer:!0,observeParents:!0});document.querySelector(".slide-0").addEventListener("click",function(){a.slideTo(0,400)}),document.querySelector(".slide-1").addEventListener("click",function(){a.slideTo(1,400)}),document.querySelector(".slide-2").addEventListener("click",function(){a.slideTo(2,400)}),document.querySelector(".slide-3").addEventListener("click",function(){a.slideTo(3,400)});var b=document.querySelectorAll(".slide-tab");a.on("slideChange",function(){var c=document.querySelector(".slide-"+a.activeIndex);Array.prototype.forEach.call(b,function(a){a.classList.remove("active-slide-tab"),c.classList.add("active-slide-tab")})})}(),function(){// event listener function
function a(a){var b=a.currentTarget.getAttribute("data-tab");for(e=0;e<f.length;e++)// deactivate all tabs
// hide all pages
f[e].classList.remove("active-tab"),h[e].classList.remove("active-page");// activate current tab
// show current page
a.currentTarget.classList.add("active-tab"),k=document.querySelector("."+b),k.classList.add("active-page"),n=new TimelineLite,n.staggerFromTo("."+b+" .q-home-apps__block",1,{y:"20%",autoAlpha:0},{y:"0%",autoAlpha:1,ease:window.Power4.easeInOut},.1)}function b(a){var b=a.currentTarget.getAttribute("data-tab"),c=a.currentTarget.getAttribute("data-menu");for(e=0;e<f.length;e++)// deactivate all tabs
// hide all pages
f[e].classList.remove("active-tab"),h[e].classList.remove("active-page");// show current page
m.classList.remove("menu-active"),l=document.querySelector("."+c),l.classList.add("active-tab"),k=document.querySelector("."+b),k.classList.add("active-page"),n=new TimelineLite,n.staggerFromTo("."+b+" .q-home-apps__block",1,{y:"20%",autoAlpha:0},{y:"0%",autoAlpha:1,ease:window.Power4.easeInOut},.1)}function c(){if(p=window.innerWidth,720>p&&!o)for(e=0;e<q.length;e++)new Swiper(q[e],{slidesPerView:"auto",centeredSlides:!1,spaceBetween:15,observer:!0,observeParents:!0,on:{init:function init(){o=1}}})}// active/current tab function
var d,e,f,g,h,k,l,m,n;for(f=document.querySelectorAll(".apps-tab"),g=document.querySelectorAll(".apps-menu-tab"),h=document.querySelectorAll(".apps-page"),m=document.querySelector(".app-category-menu-overlay"),d=0;d<f.length;d++)f[d].addEventListener("click",a),g[d].addEventListener("click",b);m.addEventListener("click",function(){m.classList.toggle("menu-active")});var o,p,q;o=0,q=document.querySelectorAll(".q-home-apps__slider"),c();var r=_.debounce(c,200);window.addEventListener("resize",r)}(),function(){"use strict";// init news and events carousel
// init home hero carousel
new Swiper(".swiper-container",{slidesPerView:"auto",navigation:{nextEl:".q-carousel-button--next",prevEl:".q-carousel-button--prev",disabledClass:"q-carousel-button--disabled"},pagination:{el:".swiper-pagination",type:"bullets"},centeredSlides:!1,spaceBetween:30}),new Swiper(".swiper-container-hero",{speed:1e3,// speed in milliseconds
effect:"slide",// 'slide' | 'fade' | 'cube' | 'coverflow' | 'flip' | 'creative' | 'cards'
slidesPerView:"auto",navigation:!1,pagination:{el:".swiper-pagination-hero",type:"bullets",clickable:!0},// autoplay: false,
autoplay:{delay:6500,// duration of each slide in ms
disableOnInteraction:!1,pauseOnMouseEnter:!0},loop:!0,autoHeight:!1})}(),function(){"use strict";var a=document.querySelectorAll(".q-home__cp-list");Array.prototype.forEach.call(a,function(a){a.addEventListener("click",function(){a.classList.contains("mobile-active")||a.classList.toggle("active"),a.classList.remove("mobile-active")})});var b=document.querySelectorAll(".q-home__security-panel-box");Array.prototype.forEach.call(b,function(a){a.addEventListener("click",function(){a.classList.contains("mobile-active")||a.classList.toggle("active"),a.classList.remove("mobile-active")})})}(),function(){"use strict";function a(){var a=document.querySelector(".vimeo-player"),c=new Vimeo.Player(a);b.classList.add("video-playing"),c.play()}var b=document.querySelector(".q-home__video-poster"),c=document.querySelector(".poster"),d=document.querySelector(".q-home__video-poster-icon");c.addEventListener("click",a),d.addEventListener("click",a)}();

//# sourceMappingURL=index.mjs.map