"use strict";(function(){"use strict";// use XMLHttpRequest
function a(){var a,c,d,e,f,h,i,j;try{if(a=JSON.parse(this.responseText),a&&"SearchResponse"===a._type){for(j=h=a.webPages.totalEstimatedMatches||0,j=0<k?(k+1).toLocaleString()+"\u2013"+(k+g).toLocaleString()+" of "+h.toLocaleString()+" results":h.toLocaleString(),e=document.getElementById("results"),e.innerHTML="<div id=\"b_tween\">\t\t\t\t<span class=\"sb_count\" data-bm=\"4\">"+j+" \t\t\t\tresults</span></div>",c=a.webPages.value.length||0,0<c&&(i=document.createElement("ol"),i.id="b_results",i.setAttribute("role","main"),i.setAttribute("aria-label","Search Results"),e.appendChild(i)),d=0;d<c;d+=1)f=a.webPages.value[d],f.displayUrl.match(/\.pdf$/)&&(f.isPDF=!0),i.innerHTML+="<li class=\"b_algo\" data-bm=\"7\">\t\t\t\t\t<div class=\"b_title\">\t\t\t\t\t"+(f.isPDF?"<span class=\"sb_doct_txt b_float\">[PDF]</span>":"")+"\t\t\t\t\t<h2 class=\"heading--4\">\t\t\t\t\t<a class=\"q-link\" href=\""+f.url+"\">\t\t\t\t\t"+f.name+"\t\t\t\t\t</a></h2></div><div class=\"b_caption\">\t\t\t\t\t<div class=\"b_attribution\"><cite>\t\t\t\t\t"+f.displayUrl+"\t\t\t\t\t</cite></div><p>\t\t\t\t\t"+f.snippet+"\t\t\t\t\t</p></div></li>";// attach pagination UI elements
h>k+g&&i.appendChild(b(h))}else throw new Error("Unexpected response: "+this.responseText)}catch(a){throw a}}function b(b){var d,e,f,h,j,l,m,n,o,p,q;// calculate how many pages of results there are
n=Math.ceil(b/g),d=document.createElement("li"),d.className="b_pag",d.setAttribute("data-bm",17),e=document.createElement("nav"),e.setAttribute("role","navigation"),d.appendChild(e),f=document.createElement("h4"),f.innerHTML="Pagination",f.className="b_hide",e.appendChild(f),h=document.createElement("ul"),h.className="sb_pagF",h.setAttribute("aria-label","More pages with results"),e.appendChild(h),o=k/g+1,p=o-2,1>p&&(p=1),q=p+4;// generate up to 5 page links based on total estimated matches
for(var r=p;r<=q;r+=1)r<=n&&(j=document.createElement("li"),l=document.createElement("a"),l.innerHTML=r,r===o?l.className="sb_pagS":(l.setAttribute("aria-label","Page "+r),l.href="#page-"+r,l.addEventListener("click",c)),h.appendChild(j.appendChild(l)));// generate prev/next links
return 1<p&&(j=document.createElement("li"),l=document.createElement("a"),l.className="sb_pagP",l.title="Previous page",l.href="#prev",l.addEventListener("click",c),m=document.createElement("div"),m.className="sw_prev",m.innerHTML="\u25C4",l.appendChild(m),j.appendChild(l),h.insertBefore(j,h.childNodes[0])),q<n&&(j=document.createElement("li"),l=document.createElement("a"),l.className="sb_pagN",l.title="Next page",l.href="#next",l.addEventListener("click",c),m=document.createElement("div"),m.className="sw_next",m.innerHTML="\u25BA",l.appendChild(m),j.appendChild(l),h.appendChild(j)),d}// handle pageination
function c(a){var b;a.preventDefault(),b=a.target.classList.contains("sw_prev")?k/g:a.target.classList.contains("sw_next")?k/g+2:parseInt(a.target.innerText,10),k=g*(b-1),d(l,k)}function d(b,c){var d,e,h;// clear old results, if any
e=document.getElementById("results"),e&&(e.innerHTML=""),c=c||0,d=new XMLHttpRequest,d.addEventListener("load",a),h=[i,"/search?q="+b,"&customconfig="+f,"&count="+g,"&offset="+c,"&responseFilter=Webpages","&mkt=en-us","&safesearch=Moderate"].join(""),d.open("GET",h),d.setRequestHeader("Ocp-Apim-Subscription-Key",j),d.send()}function e(a){var b;// get query string from input value
// make request for new results
a.preventDefault(),b=a.target.querySelector("input[name=query]"),b&&(l=b.value,k=0),d(l)}// bind the form action to trigger the XMLHttpRequest
var f,g,h,i,j,k,l;// get key and config from HTML
h=document.querySelector(".bing"),h&&(j=h.getAttribute("data-azure-subscription-key"),f=h.getAttribute("data-bing-custom-search-config-id"),g=h.getAttribute("data-bing-custom-search-results-per-page")||10),i="https://api.cognitive.microsoft.com/bingcustomsearch/v7.0",k=0;var m=document.querySelector("#search_form");m&&m.addEventListener("submit",e);// look for a query variable in the URL
var n=location.search.match(/q=(.*)([&;#]|$)/);if(n){var o=decodeURIComponent(n[1]).replace(/\+/g," ");if(o){// update input value
var p=document.querySelector("input[name=query]");// search for query
p&&(p.value=o),d(o)}}})();
//# sourceMappingURL=bing.js.map